# Generated by Django 6.0.6 on 2026-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Бургеры', 'Бургеры'), ('Пицца', 'Пицца'), ('Напитки', 'Напитки')], max_length=50, verbose_name='Категория'),
        ),
    ]
